### ISSUE TITLE
Doesn't work with res.sendFile() and templates

### ISSUE THREAD

**Issue by sergeicodes** [neverendingqs/netlify-express#3]
This workaround with `<object>` doesn't work in production neither with `res.sendFile()` nor with templates:

```js
router.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, './index.html'));
});
```

```js
router.get('/', (req, res) => {
  res.render('index', {
      title: 'Hello, World!',
      message: 'Works!'
  });
});
```

Here is an error:

<img width="347" alt="error" src="https://user-images.githubusercontent.com/10166916/50424219-337a1700-0861-11e9-9859-c74898b727cb.png">

**Comment by neverendingqs** [comment]
Hi @krigersergei,

Unfortunately, that is a limitation with Netlify functions:

> Netlify requires that each Lambda function’s code to be self-contained in one file. This means you are unable to serve any static files from Express.js, and that any view templates will have to be embedded in JavaScript files.
> ~https://blog.neverendingqs.com/2018/09/08/expressjs-on-netlify.html#static-files

I do not know of any workarounds off the top of my head. You may want to take a look at Netlify's bundler to see if you can work around this limitation: https://github.com/netlify/netlify-lambda.
